sudo: false
cache: pip

language: python
python: 3.6

stages:
  - test

jobs:
  include:
    # test stage
    - stage: test
      env: TOXENV=py

install:
- pip install tox codecov coverage

script:
- tox

after_success:
- tox -e coverage-report
- codecov

notifications:
  slack: pybel:n2KbWKBum3musnBg3L76gGwq
